name: Build on Push to Build Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'nobuild') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          # Enable BuildKit features for better caching
          driver-opts: |
            image=moby/buildkit:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            fajyz/ois-gold-runpod-worker-comfy:${{ github.sha }}
            fajyz/ois-gold-runpod-worker-comfy:latest
          platforms: linux/amd64
          target: base
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Enable BuildKit features
          build-args: |
            BUILDKIT_INLINE_CACHE=1
