name: Build Base Image on Push to Main Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'nobuild') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push base image using Docker Bake
        uses: docker/bake-action@v3
        with:
          targets: base
          push: true
          set: |
            *.platform=linux/amd64
            DOCKERHUB_REPO=fajyz
            DOCKERHUB_IMG=ois-gold-runpod-worker-comfy
            RELEASE_VERSION=${{ github.sha }}
